USE `ymtk`;

INSERT INTO lt_gifts(id,name,grade,booth,is_stock,created_at,updated_at,deleted_at) VALUES('1','サンプル景品1','A','https://hydrangeacypress.booth.pm/items/2763379',TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,null);
INSERT INTO lt_gifts(id,name,grade,booth,is_stock,created_at,updated_at,deleted_at) VALUES('2','サンプル景品2','A','https://hydrangeacypress.booth.pm/items/2763379',TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,null);
INSERT INTO lt_gifts(id,name,grade,booth,is_stock,created_at,updated_at,deleted_at) VALUES('3','サンプル景品3','B','https://hydrangeacypress.booth.pm/items/2763379',TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,null);
INSERT INTO lt_gifts(id,name,grade,booth,is_stock,created_at,updated_at,deleted_at) VALUES('4','サンプル景品4','B','https://hydrangeacypress.booth.pm/items/2763379',TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,null);
INSERT INTO lt_gifts(id,name,grade,booth,is_stock,created_at,updated_at,deleted_at) VALUES('5','サンプル景品5','C','https://hydrangeacypress.booth.pm/items/2763379',TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,null);
INSERT INTO lt_gifts(id,name,grade,booth,is_stock,created_at,updated_at,deleted_at) VALUES('6','サンプル景品6','C','https://hydrangeacypress.booth.pm/items/2763379',TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,null);
INSERT INTO lt_gifts(id,name,grade,booth,is_stock,created_at,updated_at,deleted_at) VALUES('7','サンプル景品7','D','https://hydrangeacypress.booth.pm/items/2763379',TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,null);
INSERT INTO lt_gifts(id,name,grade,booth,is_stock,created_at,updated_at,deleted_at) VALUES('8','サンプル景品8','D','https://hydrangeacypress.booth.pm/items/2763379',TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,null);
INSERT INTO lt_gifts(id,name,grade,booth,is_stock,created_at,updated_at,deleted_at) VALUES('9','サンプル景品9','D','https://hydrangeacypress.booth.pm/items/2763379',TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,null);
INSERT INTO lt_gifts(id,name,grade,booth,is_stock,created_at,updated_at,deleted_at) VALUES('10','サンプル景品10','D','https://hydrangeacypress.booth.pm/items/2763379',TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,null);
INSERT INTO lt_gifts(id,name,grade,booth,is_stock,created_at,updated_at,deleted_at) VALUES('11','サンプル景品11','E','https://hydrangeacypress.booth.pm/items/2763379',TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,null);
INSERT INTO lt_gifts(id,name,grade,booth,is_stock,created_at,updated_at,deleted_at) VALUES('12','サンプル景品12','E','https://hydrangeacypress.booth.pm/items/2763379',TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,null);
INSERT INTO lt_gifts(id,name,grade,booth,is_stock,created_at,updated_at,deleted_at) VALUES('13','サンプル景品13','E','https://hydrangeacypress.booth.pm/items/2763379',TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,null);
INSERT INTO lt_gifts(id,name,grade,booth,is_stock,created_at,updated_at,deleted_at) VALUES('14','サンプル景品14','E','https://hydrangeacypress.booth.pm/items/2763379',TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,null);
INSERT INTO lt_gifts(id,name,grade,booth,is_stock,created_at,updated_at,deleted_at) VALUES('15','サンプル景品15','E','https://hydrangeacypress.booth.pm/items/2763379',TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,null);
INSERT INTO lt_gifts(id,name,grade,booth,is_stock,created_at,updated_at,deleted_at) VALUES('16','サンプル景品16','E','https://hydrangeacypress.booth.pm/items/2763379',TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,null);
INSERT INTO lt_gifts(id,name,grade,booth,is_stock,created_at,updated_at,deleted_at) VALUES('17','サンプル景品17','E','https://hydrangeacypress.booth.pm/items/2763379',TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,null);
INSERT INTO lt_gifts(id,name,grade,booth,is_stock,created_at,updated_at,deleted_at) VALUES('18','サンプル景品18','E','https://hydrangeacypress.booth.pm/items/2763379',TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,null);
INSERT INTO lt_gifts(id,name,grade,booth,is_stock,created_at,updated_at,deleted_at) VALUES('19','サンプル景品19','E','https://hydrangeacypress.booth.pm/items/2763379',TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,null);
